rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
#  - rbx
#  - jruby
sudo: true
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
# notifications:
#   recipients:
#     - activeldap-commit@googlegroups.com
before_install:
  - travis/before_install.sh
before_script:
  - travis/before_script.sh
